name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9"]

    steps:
      - name: Check Environment Vars
        env:
          TEST_PORT: ${{ secrets.TEST_PORT }}
          TEST_SERVER: ${{ secrets.TEST_SERVER }}
          TEST_DB: ${{ secrets.TEST_DB }}
        run: |
          echo ${#TEST_PORT}
          echo ${#TEST_SERVER}
          echo ${#TEST_DB}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment-${{ matrix.python-version }}.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install dask_vertica
        run: python -m pip install -e .

      - name: Run tests
        env:
          VERTICA_USER: ${{ secrets.VERTICA_USER }}
          VERTICA_PASSWORD: ${{ secrets.VERTICA_PASSWORD }}
          VERTICA_PORT: ${{ secrets.VERTICA_PORT }}
          VERTICA_DB: ${{ secrets.VERTICA_DB }}
          VERTICA_HOST: ${{ secrets.VERTICA_HOST }}
          VERTICA_SCHEMA: ${{ secrets.VERTICA_SCHEMA }}
        run: pytest dask_vertica
