name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment-${{ matrix.python-version }}.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install dask_vertica
        run: python -m pip install -e .

      - name: Run tests
        run: pytest dask_vertica
